### ISSUE TITLE
YOUR SECRET KEY IS PUBLICLY AVAIBLE 

### ISSUE THREAD

**Issue by fabianbernhart** [Anac0n6a/Yatube#4]
workflows/....yml

```yml
- name: Test with pytest
      env:
        SECRET_KEY: "WHERE IS THE SECRET ..."
        DJANGO_SETTINGS_MODULE: yatube.settings
        DEBUG: 1
        ALLOWED_HOSTS: "*"
      run: |
        py.test
`````
